### PR TITLE
fix: adjust the kms sidecar example to IOTA network

### LINKED ISSUE #89: sample_kms_sidecar refers to SUI libraries
https://github.com/iotaledger/gas-station/tree/dev/sample_kms_sidecar 
(both scripts)

### PR DESCRIPTION
**Pull request by qrayven**
## Description

This PR removes the SUI dependency from the KMS sidecar example and makes it fully functional with IOTA-only dependencies.

### Changes Made

- Removed SUI Dependencies
- Added Comprehensive README
- Made Example Buildable and Runnable
- Ensured all dependencies are properly configured

### Current Dependencies

The KMS sidecar now uses only:
- `@aws-sdk/client-kms` - AWS KMS integration
- `@iota/iota-sdk` - IOTA SDK for transaction handling
- `@noble/curves` & `@noble/hashes` - Cryptographic operations
- `asn1-ts` - ASN.1 encoding
- `express` - Web server framework

### Testing

The example can now be built and run with:
```bash
npm install
npm run build
npm start
```

closes #89

### CODE REVIEW

File: sample_kms_sidecar/index.ts [hunk 1]
```diff
@@ -1,7 +1,7 @@
 import express from "express";
-import { fromB64 } from "@mysten/sui.js/utils";
-import { Secp256k1PublicKey } from "@mysten/sui.js/keypairs/secp256k1";
-import { getPublicKey, signAndVerify } from "./awsUtils";
+import { fromB64 } from "@iota/iota-sdk/utils";
```
Comment (wulfraem) [inline sample_kms_sidecar/index.ts]: Got a warning locally. ^^

> 'fromB64' is deprecated.

gas-station/sample_kms_sidecar/node_modules/@iota/bcs/dist/cjs/b64.d.ts:5 :

```ts
/** @deprecated use fromBase64 instead */
export declare const fromB64: typeof fromBase64;
```

File: sample_kms_sidecar/README.md [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+```bash
+npm run build
+npm start
+```
+
+### Watch Mode (for development)
+
+```bash
+npm run watch
```
Comment (wulfraem) [inline sample_kms_sidecar/README.md]: Do I need some specific setup to make that work? `ts-node` doesn't seem to support "--watch" for me.

**Review by wulfraem — CHANGES_REQUESTED** [review]

File: sample_kms_sidecar/index.ts (hunk 1 above)
Comment (qrayven) [reply sample_kms_sidecar/index.ts]: fixed

File: sample_kms_sidecar/README.md (hunk 2 above)
Comment (qrayven) [reply sample_kms_sidecar/README.md]: good catch, I haven't verified it. I removed the section along with the other one, which seems unnecessary too

Comment (wulfraem) [reply sample_kms_sidecar/README.md]: Should we remove the `package.json` [entry](https://github.com/iotaledger/gas-station/pull/119/files#diff-f2ed40c603f946179d6e5ff39434fcd7493fcba555c67eaac6f2ec1e17c9db01R10) as well or will `watch` be re-added in the future?

Comment (qrayven) [reply sample_kms_sidecar/README.md]: another good catch :). I removed it. This is an example, and we should reduce the number of targets to a minimum.

**Review by wulfraem — APPROVED** [review]
