### PR TITLE
fix gas register for over-sized gas coins 

### LINKED ISSUE #143: Oversized Coin Stays in Redis After Split, Causing Stale Registry State
**Description**  
When a sponsored transaction finishes, its change coin is written back to Redis before any rescan happens. If the coin is oversized (`balance > NEW_COIN_BALANCE_FACTOR_THRESHOLD × target_init_balance`), the scheduled rescan later consumes and splits it, so the oversized on-chain object no longer exists. However, the original Redis entry is never removed. The registry now references an object ID that the network has already spent/split, while the newly created small coins are added alongside it—leaving Redis with a stale record.

**Impact**  
- **Stale allocations**: Future reservations can pick the oversized entry and hit `Object not found` errors before the split shards are used.  
- **Double accounting**: Until the stale entry is cleaned up, Redis shows more liquidity than the network actually owns.  
- **Operational churn**: Repeat occurrences require manual Redis cleanup or trigger cascading rescans/failed executions.

### PR DESCRIPTION
**Pull request by qrayven**
The PR implements an automatic detection and splitting mechanism with four key components:

1. **Oversized Coin Detection**: Checks if returned coins exceed `200 × target_init_balance`

2. **Automatic Rescan Trigger**: New `RescanGasObjectsTrigger` component that:
   - Triggers rescan when oversized coins are detected
   - Uses buffered channel to handle concurrent requests
   - Prevents oversized coins from polluting the pool

3. **Enhanced Metrics**: Three new Prometheus metrics:
   - `reserved_gas_real_gas_usage_delta` - tracks gas over-reservation
   - `gas_usage_per_transaction` - tracks actual consumption
   - `oversized_gas_coins_count` - counts oversized occurrences

4. **Documentation**: Comprehensive troubleshooting guide in `docs/common-issues.md`

closes #143

### CODE REVIEW

File: src/gas_station/gas_station_core.rs [hunk 1]
```diff
@@ -161,10 +174,30 @@ impl GasStation {
...
+            coin.balance
+                > NEW_COIN_BALANCE_FACTOR_THRESHOLD * self.rescan_config.target_init_balance
+        });
+        if contains_oversized_coins {
+            warn!("Oversized coins found during transaction execution. Initiating rescan to split these coins. If this occurs frequently, consider adjusting target_init_balance or the maximum transaction budget.");
+            self.rescan_config.trigger_rescan().await;
+            self.metrics
+                .oversized_gas_coins_count
+                .with_label_values(&[&sponsor.to_string()])
+                .inc_by(updated_coins.len() as u64);
```
Comment (wulfraem) [inline src/gas_station/gas_station_core.rs]: Should we update by a filtered value of `updated_coins` here?

The Error match arm of `let updated_coins = match &response {` should return all (updated) coins from `payment`, regardless of size, right?

File: src/gas_station_initializer.rs [hunk 2]
```diff
@@ -213,24 +215,42 @@ impl GasStationInitializer {
...
+        mut rescan_trigger_receiver: tokio::sync::mpsc::Receiver<()>,
     ) {
+        let mut ticker =
+            tokio::time::interval(Duration::from_secs(coin_init_config.refresh_interval_sec));
+        ticker.set_missed_tick_behavior(MissedTickBehavior::Skip);
+
         loop {
-            tokio::select! {
-                _ = tokio::time::sleep(Duration::from_secs(coin_init_config.refresh_interval_sec)) => {}
+            let wake_reason = tokio::select! {
```
Comment (wulfraem) [inline src/gas_station_initializer.rs:241]: Not 100% required, but was thinking that using an `enum` for `wake_response` might be a bit cleaner. It looks slightly confusing to have a wake reason `None` (so waking up for no reason :D) breaking/canceling the task (so there _was_ a reason :D). And for the moment, we know, that we have 3 separate reasons, so no real need for a "free text field" with `Some(static_string_anyway)`. ^^

**Review by wulfraem — CHANGES_REQUESTED** [review]

File: src/gas_station/gas_station_core.rs (hunk 1 above)
Comment (qrayven) [reply src/gas_station/gas_station_core.rs]: totally right, Thanks, fixed

File: src/gas_station_initializer.rs (hunk 2 above)
Comment (qrayven) [reply src/gas_station_initializer.rs:241]: good point, the `enum` `WakeReason`  is also consistent with the `RunMode`. Refactored

**Review by wulfraem — APPROVED** [review]
